# Generated by Django 3.2.3 on 2024-10-31 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000, message='Объем ингредиента не должен быть больше 1000.'), django.core.validators.MinValueValidator(1, message='Объем ингредиента не должен быть меньше 1.')]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(1000, message='Время приготовления не должно быть больше 1000.'), django.core.validators.MinValueValidator(1, message='Время приготовления не должно быть меньше 1.')], verbose_name='время приготовления'),
        ),
    ]
